#! /usr/bin/env bash

here=`pwd`


mkdir -p $here/lib/

cp `find . -type f -wholename "*.a"` ./lib

#generate a static library using all *.o generated by painless
ar -rv lib/libpainless.a `find . -type f -wholename "*.o*"`
cd 

