all:
	$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build"
kissat:
	$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build" kissat
tissat:
	$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build" tissat
clean:
	rm -f "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat"/makefile
	-$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build" clean
	rm -rf "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build"
coverage:
	$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build" coverage
indent:
	$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build" indent
test:
	$(MAKE) -C "/home/nissa/Documents/Thesis/bmctool_main/octo_bmctool/bmctool/painless/kissat/build" test
.PHONY: all clean coverage indent kissat test tissat
